env:
  browser: true
  es2021: true
parser: '@typescript-eslint/parser'
extends:
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - standard
  - 'plugin:prettier/recommended'
globals:
  React: true
  ReactDOM: true
  p5: true
  ReactP5Wrapper: true
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {
  'react/prop-types': 'off',
  'import/no-absolute-path': 'off',
  '@typescript-eslint/ban-ts-comment': 'off'
}
